## YAML Template.
language: php
php:
  - 5.6

before_script:
  - composer self-update
  - composer install
  
after_script:
  - vendor/bin/phpcs app/ --standard=PSR2
  - vendor/bin/phpcpd app/
  - vendor/bin/phpmd app text codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpunit test/
